### PR TITLE
[bug: #19, #22] Fix examples and v27 Jest support / ESM

### LINKED ISSUE #19: svelte-jester 2.x does not work
svelte-jester 2.x does not work with jest 27, see https://github.com/mihar-22/svelte-jester/issues/65

Solution: Downgrade to

"ts-jest": "26.5.6",
"jest": "26.6.3",
"svelte-jester": "1.8.2",

### LINKED ISSUE #22: generate test file option generates nothing
I answered the following:
```
[ question ]  Enable Jest DOM support? (Y/n) · false
[ question ]  Enable TypeScript support? (y/N) · false
[ question ]  Generate example test file? (Y/n) · true
```

No example test file was generated. It should either not ask the last question or generate a test file that doesn't depend on the DOM

### PR DESCRIPTION
**Pull request by rossyman**
Fix examples and v27 Jest support / ESM.

- Resolves #19 
- Resolves #22

### Changelog
- Add new `--jsdom` flag / option
    - Enables the user to specify whether they want per-test environment config with `@jest-environment` data-block, or to default to `jsdom` within `jest.config.json`.
- Ensure Jest DOM `@types` are only installed if both `ts` and `jest-dom` option are true
- Add ESM specific configuration for Jest:
    - Use `--experimental-vm-modules` flag when running Jest
    - Enable `useESM` configuration property for `ts-jest`
    - Force `.mjs` transformer usage in `jest.config.json` for `svelte-jester`. See https://github.com/rossyman/svelte-add-jest/issues/19#issuecomment-916218761
    - Add `.svelte` extensions to Jest `extensionsToTreatAsEsm`; and `.ts` depending on the TS option
- Improve example test files for a mixture of TS, JS and JS DOM configurations
- Remove divergence of `lib` property within `tsconfig.spec.json` to extend from `tsconfig.json`

### CODE REVIEW

**Review by braebo — APPROVED** [review]

File: preset.ts [hunk 1]
```diff
@@ -197,33 +200,50 @@ class SvelteJestAdder extends Adder {
     Preset
       .editJson('jest.config.json').merge({
         transform: {
-          '^.+\\.svelte$': ['svelte-jester', {preprocess: true}],
+          '^.+\\.svelte$': ['./node_modules/svelte-jester/dist/transformer.mjs', {preprocess: true}],
```
Comment (benmccann) [inline preset.ts:203]: Can this not be just `svelte-jester`?

File: templates/index.spec.ts [hunk 2]
```diff
@@ -1,12 +1,24 @@
...
+
+    test('should be true', () => {
+      expect(isTestSuitePassing).toBe(true);
+    });
+
+  });
 
-test('shows proper heading when rendered', () => {
-  const { getByText } = render(index);
-  expect(getByText('Hello world!')).toBeInTheDocument();
```
Comment (benmccann) [inline templates/index.spec.ts:11]: I liked that this was testing the `.svelte` file before, but it was challenging that the content was not the same in the two SvelteKit templates. Perhaps we can update the SvelteKit templates so that there's some piece of shared content to solve that?

Comment (braebo) [reply templates/index.spec.ts:11]: Perhaps we could just test for `Sveltekit`?  That would pass both templates.

Comment (benmccann) [reply templates/index.spec.ts:11]: That sounds like a good solution to me!

File: preset.ts (hunk 1 above)
Comment (benmccann) [reply preset.ts:203]: Ah, I just saw your explanation on https://github.com/rossyman/svelte-add-jest/issues/19#issuecomment-916218761

File: templates/index.spec.ts (hunk 2 above)
Comment (rossyman) [reply templates/index.spec.ts:11]: Yeah so I can rework the tests slightly to just look for "Sveltekit".

For non Jest DOM users, we can just use the `toBeDefined()` matcher on the result of `getByText()`, and similarly continue to use `toBeInTheDocument()` for Jest DOM users -- does sound like a better solution?

File: preset.ts (hunk 1 above)
Comment (rossyman) [reply preset.ts:203]: Yeah it's a rather peculiar issue. I would've assumed that Jest would've somehow picked up the `.mjs` file automagically when the ESM flag is enabled, but it seems to be forcing the `.cjs` transformer usage.

File: templates/index.spec.ts (hunk 2 above)
Comment (benmccann) [reply templates/index.spec.ts:11]: yeah, that sounds like a good idea

**Comment by benmccann** [comment]
Just FYI, we're planning on bringing back CJS support to `svelte-jester` in https://github.com/mihar-22/svelte-jester/pull/71. I think that ESM is probably the better default for SvelteKit projects though, so this is still a good change. Possibly some people will want it as an option, but we can see how this goes
